name: Remove older release images

on:
  push:
    branches:
      - dpl-785-remove-old-releases

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  remove-old-packages:
    name: Remove the older packages
    runs-on: ubuntu-latest
    steps:
        # The delete-package-versions action has become broken and the fix doesn't look imminent.
        # Re-enable this later if a fix comes out! https://github.com/actions/delete-package-versions/issues/28
        # if: false
        # uses: actions/delete-package-versions@v1
        # with:
        #   package-name: "${{ github.event.repository.name }}"

        uses: actions/delete-package-versions@v4
        with:
          package-name: "${{ github.event.repository.name }}"
          package-type: 'container'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: "true"
